const USERS = [
  { email: 'empleado@romera.com', password: 'romera123', name: 'Lucía Fernández', role: 'employee' },
  { email: 'admin@romera.com', password: 'romera123', name: 'Gisella', role: 'admin' }
];
const BRANCHES = ['Balcarce', 'Colón', 'Salta', 'Tandil', 'Necochea'];
const ORIGINS = ['Centralize Whatsapp', 'Centralize Mailzing', 'Mail Lastenia', 'Recepción escritorio', '0800/0810', 'Rep. Mostrador'];
const TYPES = ['Accesorio', 'Garantía Extendida', 'Contrato'];
const initialSales = [
  {id:1,date:'2026-09-12',branch:'Balcarce',employee:'Lucía Fernández',origin:'Centralize Whatsapp',plate:'AF 123 BC',order:'ORD-4582',type:'Accesorio',status:'Pendiente',file:''},
  {id:2,date:'2026-09-10',branch:'Tandil',employee:'Martín Pérez',origin:'Recepción escritorio',plate:'AG 456 DE',order:'',type:'Contrato',status:'Aprobada',file:'comprobante_pago.pdf'},
  {id:3,date:'2026-09-07',branch:'Necochea',employee:'Lucía Fernández',origin:'0800/0810',plate:'AH 789 FG',order:'ORD-4471',type:'Garantía Extendida',status:'Aprobada',file:'orden_firmada.jpg'}
];
const root=document.querySelector('#app');
let currentUser=JSON.parse(localStorage.getItem('romera_user')||'null');
let sales=JSON.parse(localStorage.getItem('romera_sales')||'null')||initialSales;
sales=sales.map(s=>({...s,branch:s.branch||'',origin:s.origin||'',plate:s.plate||'',order:s.order||'',type:s.type||s.product||'',date:s.date||''}));
function persist(){localStorage.setItem('romera_sales',JSON.stringify(sales));}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('');}
function date(s){return s?new Date(s+'T12:00').toLocaleDateString('es-AR'):'—';}
function options(items,prompt){return `<option value="">${prompt}</option>${items.map(x=>`<option>${x}</option>`).join('')}`;}
function badge(t){return `<span class="badge ${t==='Contrato'?'maintenance':t==='Garantía Extendida'?'warranty':''}">${esc(t)}</span>`;}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2800);}
function layout(content){return `<div class="shell"><header><div class="brand"><span class="brand-mark">R</span> ROMERA <span style="font-weight:500;color:#789087">| Postventa</span></div><div class="user-chip"><div class="avatar">${initials(currentUser.name)}</div><span>${currentUser.name}<br><small style="color:#65726b">${currentUser.role==='admin'?'Administración':'Asesor de ventas'}</small></span><button class="logout" id="logout">Salir</button></div></header><section class="content">${content}</section></div>`;}
function login(){root.innerHTML=`<section class="auth"><div class="auth-hero"><div class="brand"><span class="brand-mark">R</span> ROMERA HNOS.</div><div><div class="eyebrow" style="color:#c8ed85">Postventa</div><h1>Gestión interna de ventas.</h1><p>Un único espacio para registrar y consultar las operaciones del equipo de postventa.</p></div><div class="hero-footer">Romera Hnos. · Postventa · Gestión interna de ventas</div></div><div class="login-wrap"><form class="login" id="loginForm"><div class="eyebrow">Acceso al sistema</div><h2>Bienvenido</h2><p>Ingresá con tu correo corporativo.</p><label class="field">Correo electrónico<input name="email" type="email" placeholder="nombre@romera.com" required></label><label class="field">Contraseña<input name="password" type="password" placeholder="••••••••" required></label><div id="loginError" class="error"></div><button class="primary" type="submit">Ingresar</button><div class="demo"><strong>Accesos de demostración</strong><br>Empleado: empleado@romera.com<br>Administración: admin@romera.com<br>Contraseña: romera123</div></form></div></section>`;document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),u=USERS.find(x=>x.email===f.get('email').trim().toLowerCase()&&x.password===f.get('password'));if(!u){document.querySelector('#loginError').textContent='El correo o la contraseña no son correctos.';return;}currentUser=u;localStorage.setItem('romera_user',JSON.stringify(u));render();};}
function employee(){const own=sales.filter(s=>s.employee===currentUser.name);root.innerHTML=layout(`<div class="page-head"><div><div class="eyebrow">Mi espacio</div><h1>Registrá una nueva venta</h1><p>La información quedará disponible para que Administración gestione la liquidación.</p></div></div><div class="stats"><div class="stat"><small>Ventas registradas</small><span class="number">${own.length}</span></div><div class="stat"><small>Contratos cargados</small><span class="number">${own.filter(s=>s.type==='Contrato').length}</span></div><div class="stat"><small>Pendientes de revisar</small><span class="number">${own.filter(s=>s.status==='Pendiente').length}</span></div></div><div class="grid"><div class="card"><h3>Nueva operación</h3><p class="intro">Los campos con * son obligatorios. En contratos se exige el comprobante de pago.</p><form id="saleForm"><div class="form-grid"><label class="field">Sucursal *<select name="branch" required>${options(BRANCHES,'Seleccioná una sucursal')}</select></label><label class="field">Vendedor<input value="${esc(currentUser.name)}" disabled><input name="employee" value="${esc(currentUser.name)}" type="hidden"></label><label class="field full">Origen *<select name="origin" required>${options(ORIGINS,'Seleccioná el origen')}</select></label><label class="field">Placa *<input name="plate" list="plates" placeholder="Ej.: AF 123 BC" required><datalist id="plates"><option value="AF 123 BC"><option value="AG 456 DE"><option value="AH 789 FG"></datalist></label><label class="field">Fecha de carga *<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label class="field">N° de orden<input name="order" placeholder="Opcional"></label><label class="field">Tipo *<select name="type" id="saleType" required>${options(TYPES,'Seleccioná el tipo')}</select></label><label class="field full">Archivo adjunto <span id="attachmentRequired"></span><div class="upload">Adjuntá el comprobante o imagen de respaldo<input id="proof" name="proof" type="file" accept=".pdf,image/*"></div><div id="fileNote" class="file-note"></div></label></div><div class="form-actions"><button class="primary">Guardar venta</button></div></form></div><div class="card"><h3>Mis últimas cargas</h3><p class="intro">Estado de las ventas enviadas a Administración.</p><div class="table-wrap" style="margin-top:20px">${table(own.slice().sort((a,b)=>b.id-a.id),false)}</div></div></div>`);const rule=()=>{const contract=document.querySelector('#saleType').value==='Contrato',input=document.querySelector('#proof');input.required=contract;document.querySelector('#attachmentRequired').textContent=contract?'* Obligatorio para contratos':'(opcional)';};document.querySelector('#saleType').onchange=rule;document.querySelector('#proof').onchange=e=>document.querySelector('#fileNote').textContent=e.target.files[0]?`Adjunto: ${e.target.files[0].name}`:'';document.querySelector('#saleForm').onsubmit=saveSale;rule();bindCommon();}
function table(rows,admin){if(!rows.length)return '<div class="empty">Todavía no hay ventas para mostrar.</div>';return `<table class="sales-table"><thead><tr><th>Fecha</th><th>Sucursal</th>${admin?'<th>Vendedor</th>':''}<th>Origen</th><th>Placa</th><th>N° orden</th><th>Tipo</th>${admin?'<th>Adjunto</th>':''}<th>Estado</th>${admin?'<th></th>':''}</tr></thead><tbody>${rows.map(s=>`<tr><td>${date(s.date)}</td><td>${esc(s.branch)||'—'}</td>${admin?`<td><strong>${esc(s.employee)}</strong></td>`:''}<td>${esc(s.origin)||'—'}</td><td><strong>${esc(s.plate)||'—'}</strong></td><td>${esc(s.order)||'—'}</td><td>${badge(s.type)}</td>${admin?`<td>${s.file?'📎 '+esc(s.file):'—'}</td>`:''}<td><span class="status ${s.status==='Aprobada'?'approved':s.status==='Rechazada'?'rejected':''}"><i class="dot"></i>${s.status}</span></td>${admin?`<td><select class="status-select" data-id="${s.id}"><option ${s.status==='Pendiente'?'selected':''}>Pendiente</option><option ${s.status==='Aprobada'?'selected':''}>Aprobada</option><option ${s.status==='Rechazada'?'selected':''}>Rechazada</option></select></td>`:''}</tr>`).join('')}</tbody></table>`;}
function admin(){const pending=sales.filter(s=>s.status==='Pendiente').length;root.innerHTML=layout(`<div class="page-head"><div><div class="eyebrow">Administración</div><h1>Ventas para liquidación</h1><p>Revisá, aprobá y descargá las operaciones informadas por el equipo.</p></div><button id="export" class="secondary">Descargar planilla CSV</button></div><div class="stats"><div class="stat"><small>Operaciones del período</small><span class="number">${sales.length}</span></div><div class="stat"><small>Contratos cargados</small><span class="number">${sales.filter(s=>s.type==='Contrato').length}</span></div><div class="stat"><small>Pendientes de revisar</small><span class="number">${pending}</span></div></div><div class="card"><div class="admin-tools"><div><h3>Operaciones registradas</h3><p class="intro">Actualizá el estado una vez validada la información.</p></div><div class="filters"><input id="search" placeholder="Buscar placa o vendedor"><select id="branchFilter">${options(BRANCHES,'Todas las sucursales')}</select><select id="typeFilter">${options(TYPES,'Todos los tipos')}</select><select id="statusFilter"><option value="">Todos los estados</option><option>Pendiente</option><option>Aprobada</option><option>Rechazada</option></select></div></div><div id="results" class="table-wrap">${table(sales.slice().sort((a,b)=>b.id-a.id),true)}</div></div>`);const filter=()=>{const q=document.querySelector('#search').value.toLowerCase(),branch=document.querySelector('#branchFilter').value,type=document.querySelector('#typeFilter').value,status=document.querySelector('#statusFilter').value,result=sales.filter(s=>(!q||[s.employee,s.plate,s.order,s.origin].join(' ').toLowerCase().includes(q))&&(!branch||s.branch===branch)&&(!type||s.type===type)&&(!status||s.status===status));document.querySelector('#results').innerHTML=table(result.slice().sort((a,b)=>b.id-a.id),true);bindStatus();};['#search','#branchFilter','#typeFilter','#statusFilter'].forEach(x=>document.querySelector(x).oninput=filter);document.querySelector('#export').onclick=exportCsv;bindStatus();bindCommon();}
function bindStatus(){document.querySelectorAll('.status-select').forEach(el=>el.onchange=()=>{sales.find(s=>s.id===Number(el.dataset.id)).status=el.value;persist();toast('Estado actualizado');});}
function saveSale(e){e.preventDefault();const f=new FormData(e.target),file=document.querySelector('#proof').files[0];if(f.get('type')==='Contrato'&&!file){toast('Para registrar un contrato debés adjuntar el comprobante de pago.');return;}sales.push({id:Date.now(),date:f.get('date'),branch:f.get('branch'),employee:currentUser.name,origin:f.get('origin'),plate:f.get('plate').trim().toUpperCase(),order:f.get('order').trim(),type:f.get('type'),status:'Pendiente',file:file?file.name:''});persist();toast('La venta fue registrada correctamente');employee();}
function exportCsv(){const h=['Fecha de carga','Sucursal','Vendedor','Origen','Placa','N° de Orden','Tipo','Estado','Archivo adjunto'],data=sales.map(s=>[s.date,s.branch,s.employee,s.origin,s.plate,s.order,s.type,s.status,s.file]),csv=[h,...data].map(row=>row.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`ventas-postventa-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('La planilla se descargó correctamente');}
function bindCommon(){document.querySelector('#logout').onclick=()=>{localStorage.removeItem('romera_user');currentUser=null;render();};}
function render(){if(!currentUser)login();else currentUser.role==='admin'?admin():employee();}render();
